
version: '2'
services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    networks:
      - hangout-network

  kafka:
    container_name: kafka
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-reporter:1:1"
#      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_HOST_NAME: "kafka"
#      KAFKA_ADVERTISED_HOST_NAME: kafka
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
    networks:
      - hangout-network
#        ipv4_address: 172.17.0.2

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:2.4.0
    ports:
        - "9300:9300"
        - "9200:9200"
    expose:
        - 9200
        - 9300
    environment:
  #        限制内存使用
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "http.host=0.0.0.0"
      - "transport.host=127.0.0.1"
    networks:
        - hangout-network

  hangout:
    container_name: hangout
    image: hangout:latest
    links:
      - zookeeper:zookeeper
      - kafka:kafka
      - elasticsearch
    depends_on:
      - zookeeper
      - kafka
      - elasticsearch
    networks:
      - hangout-network

  hangout-example:
    container_name: hangout-example
    image: hangout-example:latest
    links:
      - zookeeper:zookeeper
      - kafka:kafka
    depends_on:
      - zookeeper
      - kafka
    networks:
      - hangout-network

#  kafka-manager:
#    image: sheepkiller/kafka-manager:latest
#    ports:
#      - "9000:9000"
#    links:
#      - zookeeper
#      - kafka
#    environment:
#      ZK_HOSTS: zookeeper:2181
#      APPLICATION_SECRET: hg
#      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks:
        - hangout-network
networks:
  hangout-network:
    driver: bridge
#    ipam:
#      driver: default
#      config:
#        - subnet: 172.10.0.0/16
#          gateway: 172.10.0.254
